#!/bin/sh

alias lc='colorls'
alias email='chromium-browser https://outlook.office365.com/mail/inbox'
alias sp='chromium-browser https://nxp1.sharepoint.com/teams/25_33/Shared%20Documents/Forms/AllItems.aspx?viewid=d0a8f7a4%2D6fc5%2D42ce%2Daec0%2Dd433203d8d8f&id=%2Fteams%2F25%5F33%2FShared%20$'
alias sdk='cd /media/cooper/KINGSTON/sln-vizn-iot-sdk; code ~/Documents/Code/vizn/ &'
#alias jlink='/usr/bin/JLinkExe'
alias src='source ~/.zshrc'
