-- Generated by hyprmoncfg

hl.monitor({
	output = "desc:HP Inc. HP Z27k G3 CN432218RY",
	mode = "3840x2160@60.00",
	position = "6240x0",
	scale = 1.5,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.monitor({
	output = "desc:HP Inc. HP Z27k G3 CN4322194X",
	mode = "3840x2160@60.00",
	position = "4800x-560",
	scale = 1.5,
	transform = 3,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.monitor({
	output = "desc:Samsung Display Corp. 0x41B3 0x0000FF01",
	disabled = true,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:HP Inc. HP Z27k G3 CN432218RY", persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:HP Inc. HP Z27k G3 CN4322194X", persistent = true })
