-- Generated by hyprmoncfg

hl.monitor({
	output = "desc:Samsung Display Corp. 0x41B3 0x0000FF01",
	mode = "2880x1800@120.00",
	position = "1760x1520",
	scale = 1.5,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})
