#!/bin/bash

yes_no() {
	read -r -p "$1 [y/N] " response
	case "$response" in
	[yY][eE][sS] | [yY])
		return 0
		;;
	*)
		return 1
		;;
	esac
}

# Running install Scripts
setup_shell() {
	if ! yes_no "Set zsh as default shell?"; then
		return
	fi

	if ! command -v zsh &>/dev/null; then
		echo "zsh not found on current system. Installing zsh..."
		sudo apt install zsh
	fi
	echo "Setting zsh as default shell"
	chsh -s "$(which zsh)"
}

install_dev_tools() {
	if ! yes_no "Install build_tools?"; then
		return
	fi

	sudo apt update
	# todo: move fzf and ripgrep to tea/nix and create symlink/hardlink
	tools=(build-essential fzf ripgrep)
	for tool in "${tools[@]}"; do
		echo "Installing ${tool}..."
		sudo apt install "${tool}"
	done
}

setup_shell
install_dev_tools
