# Shared helpers for the dotfiles bats suites. Loaded via `load helpers/common`.
# Plain bats built-ins only — Debian doesn't package bats-assert/bats-support.

export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$PATH"

DOTFILES_REPO=/src/dotfiles

# chezmoi against the mounted source; config was generated by harness.sh.
chez() {
    chezmoi --source "$DOTFILES_REPO" --no-tty "$@"
}

# Container distro identity from os-release (e.g. "arch", "debian").
distro_id() {
    # shellcheck disable=SC1091
    (. /etc/os-release && echo "$ID")
}
