-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                 CachyOS Hyprland Configuration              ┃
-- ┃                       (Lua format, 0.55+)                   ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
--
-- Each require() loads in its own Lua scope so a syntax error in one module
-- doesn't take down the rest of the config.

-- Visual styling: general/group/misc/render/dwindle/master/decoration/animations
require("config.appearance")

-- Monitor profiles (generated by hyprdynamicmonitors — do not edit by hand)
require("config.monitors")

-- Input, cursor, touchpad, gestures, binds {} settings
require("config.input")

-- Window rules (quake terminal, etc.)
require("config.windowrules")

-- Key + mouse bindings and the resize submap
require("config.keybinds")

-- Environment variables and exec-once startup chain
require("config.autostart")
