[aws]
symbol = "  "

[c]
symbol = ""
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[cmake]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
diverged = '[⇡$ahead_count ⇣$behind_count]'
ahead="⇡$count"
behind="⇣$count"
format = '[$all_status$ahead_behind ]($style)'
stashed = ''

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

