#!/bin/bash

# Batch file to build an Eclipse project from the command line on Windows
# Example for using MCUXpresso IDE

# path to GNU tools and compiler: arm-none-eabi-gcc.exe, ....
TOOLCHAIN_PATH=/usr/local/mcuxpressoide/ide/tools/bin

# variable to the command line Eclipse IDE executable
IDE=/usr/local/mcuxpressoide/ide/mcuxpressoide

if [[ -z $1 ]]; then
    echo "No path specified, using cwd"
    CUR_DIR="$(pwd -P)"
    echo "CUR_DIR: ${CUR_DIR}"
fi

echo "CWD: ${CUR_DIR}"
# To retrieve the workspace name and extract the project name
MCUX_WORKSPACES_FOLDER=/mnt/hdd/Users/CooperHDD/Documents/Code/MCUX

MCUX_PROJECT_PATH="${CUR_DIR#$MCUX_WORKSPACES_FOLDER/*/*/}"
# echo "MCUXPresso Project Path: ${MCUX_PROJECT_NAME}"
cd ${MCUX_PROJECT_PATH}/Debug
export PATH=${TOOLCHAIN_PATH}:${PATH}
make -j${nproc}
exit 0

# Use below to build directly from MCUXpresso IDE. Was having issues with this not exiting properly, but may automatically build some make files so this may be the better route to go
MCUX_PROJECT_PATH="${CUR_DIR#$MCUX_WORKSPACES_FOLDER/*/}"
# echo "inter Project name: $MCUX_PROJECT_NAME"
MCUX_PROJECT_NAME=$(echo $MCUX_PROJECT_NAME | cut -d / -f 1)
# MCUX_PROJECT_NAME="${MCUX_PROJECT_NAME%*}"
echo "Project name: $MCUX_PROJECT_NAME"
CUR_MCUX_WORKSPACE_PATH=${CUR_DIR%$MCUX_PROJECT_NAME*}
echo "Workspace path: ${CUR_MCUX_WORKSPACE_PATH}"
# echo "Proj: $MCUX_PROJECT_NAME";

# ECHO Extending PATH if not already present
# ECHO %PATH%|findstr /i /c:"%TOOLCHAIN_PATH:"=%">nul || set PATH=%PATH%;%TOOLCHAIN_PATH%
# WORKSPACE

# ECHO Launching Eclipse IDE
${IDE} -nosplash --launcher.suppressErrors -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ${CUR_MCUX_WORKSPACE_PATH} -cleanBuild ${MCUX_PROJECT_NAME}
