[aws]
symbol = "  "

[c]
symbol = ""
format = '[[$symbol ($version) ](fg:#769ff0)]($style)'

[cmd_duration]
style = "bold green"

[cmake]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
truncation_length = 8
truncate_to_repo = false
# style = 'bold green'
# format = '[$path]($style)[$read_only]($read_only_style) '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch) ](fg:yellow)"

[git_status]
diverged = '\[⇡$ahead_count⇣$behind_count\]'
ahead = "⇡$count"
behind = "⇣$count"
format = "[$modified$untracked$deleted$staged $ahead_behind ]($style)"
stashed = ''

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
disabled = false

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
